[env]
TERM = "xterm-256color"

[general]
live_config_reload = true

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.95

[window.padding]
x = 5
y = 3

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11.0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = '(\\w+://\\S+)'
binding = { key = "U", mods = "Control|Shift" }
mouse = { enabled = true, mods = "None" }

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}'
binding = { key = "E", mods = "Control|Shift" }
mouse = { enabled = true, mods = "None" }

[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#c8c093'

[colors.bright]
black = '#a6a69c'
red = '#e46876'
green = '#87a987'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#c5c9c5'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'
